import type { ReleaseSnapshot } from './types';

/**
 * v1.1.0 — FitStage typography pass + StepsChain3D finalization.
 *
 * IMMUTABLE SNAPSHOT. This file documents what shipped under the
 * `v1.1.0` git tag. Do not edit fields after the tag is pushed except
 * to correct a factual error in the historical record (and note the
 * correction inline). New work goes in a new `vX_Y_Z.ts` file.
 */
export const RELEASE_V1_1_0: ReleaseSnapshot = {
  version: '1.1.0',
  tag: 'v1.1.0',
  title: 'FitStage typography + StepsChain3D finalization',
  summary:
    'Deck-wide typography rebalanced for FitStage downscale headroom, ' +
    'StepsChain3D finalized (rail axis, click-only nav, cause-tagged ' +
    'transitions, broadened detail panel slide-in), and release ' +
    'workflow now ships zip + tar.gz + SHA256SUMS as Release assets.',
  releasedAt: '2026-04-30',
  frozen: true,
  build: {
    status: 'pass',
    durationSec: 14.9,
    builtAt: '2026-04-30',
    notes: [
      '`bun run build` exit code 0',
      'Vite chunk-size warning is informational (not a regression)',
      'No type errors, no schema drift',
    ],
  },
  checklist: [
    {
      id: 'version',
      label: 'Bump version in package.json',
      detail: 'Set to "1.1.0" — read live from package.json by this page.',
      status: 'done',
    },
    {
      id: 'changelog',
      label: 'Write release notes in readme.md',
      detail:
        'v1.1.0 section covers FitStage typography pass + StepsChain3D ' +
        'finalization + repo hygiene.',
      status: 'done',
    },
    {
      id: 'badge',
      label: 'Update README version badge',
      detail:
        'Generated by `bun run badge` from package.json. Idempotent; runs ' +
        'on `npm version` lifecycle.',
      status: 'done',
    },
    {
      id: 'memory',
      label: 'Memory rules + RCA logs',
      detail:
        'mem://design/fitstage-type-headroom, mem://design/step-row-motion-parity. ' +
        'Issues 22, 23, 24, 26 logged.',
      status: 'done',
    },
    {
      id: 'build',
      label: 'Production build green',
      detail: 'Last verified 2026-04-30, 14.9s.',
      status: 'done',
    },
    {
      id: 'tag',
      label: 'Create git tag v1.1.0',
      detail:
        'Run locally — sandbox cannot perform stateful git operations. ' +
        'Commands below.',
      status: 'manual',
    },
    {
      id: 'push',
      label: 'Push tag to origin',
      detail: '`git push origin v1.1.0` after the tag is created.',
      status: 'manual',
    },
    {
      id: 'release',
      label: 'Publish GitHub Release',
      detail:
        'Workflow `.github/workflows/release.yml` auto-attaches dist zip + ' +
        'tar.gz + SHA256SUMS once the tag is pushed.',
      status: 'manual',
    },
  ],
  tagCommand: `# Make sure you have the latest main from Lovable's GitHub sync
git pull origin main

# Annotated tag pinned to the v1.1.0 commit
git tag -a v1.1.0 -m "Release v1.1.0 — FitStage typography pass + StepsChain3D finalization"

# Push the tag to the remote so GitHub Releases can pick it up
git push origin v1.1.0

# Optional: verify
git tag --list 'v1.*' --sort=-v:refname
`,
  readmeAnchor: 'v110',
};
